In [ ]:
# ======================================================================= #
# Course: Deep Learning Complete Course (CS-501)
# Author: Dr. Saad Laouadi
# Lesson: Feed Forward Propagation: Numerical Example
#
# Description: This program provides an overview of dictionary comprehensions
#              and demonstrates multiple use cases, including transforming
#              data, filtering keys and values, and creating dictionaries
#              from lists.
#
# =======================================================================
#.          Copyright © Dr. Saad Laouadi
# =======================================================================

In [2]:
# Impport necessary modules
import numpy as np

In [3]:
def sigmoid(x):
    """
    The sigmoid function. # docstring
    """
    return 1 / (1 + np.exp(-x))

In [4]:
# Input
x = np.array([0.3, 0.5, 0.2])
print(x)
print(x.shape)

[0.3 0.5 0.2]
(3,)


In [5]:
# Weights and biases
W1 = np.array([[0.5, 0.4, 0.3],
               [0.4, 0.3, 0.2]])

b1 = np.array([0.4, 0.4])

W2 = np.array([[0.6, 0.7]])
b2 = np.array([0.3])

print(W1)
print(W2)

[[0.5 0.4 0.3]
 [0.4 0.3 0.2]]
[[0.6 0.7]]


In [6]:
# Forward propagation
print("Forward Propagation:")
print("-" * 50)

# Hidden layer
print("Hidden Layer Computation:")
z1 = np.dot(W1, x) + b1
print(f"z1 = np.dot(W1, x) + b1 =\n{z1}")

Forward Propagation:
--------------------------------------------------
Hidden Layer Computation:
z1 = np.dot(W1, x) + b1 =
[0.81 0.71]


In [7]:
a1 = sigmoid(z1)
print(f"\na1 = sigmoid(z1) =\n{a1}")


a1 = sigmoid(z1) =
[0.6921095  0.67040116]


In [8]:
print("\n" + "-" * 50)

# Output layer
print("Output Layer Computation:")
z2 = np.dot(W2, a1) + b2
print(f"z2 = np.dot(W2, a1) + b2 =\n{z2}")


--------------------------------------------------
Output Layer Computation:
z2 = np.dot(W2, a1) + b2 =
[1.18454651]


In [9]:
y = sigmoid(z2)
print(f"\ny = sigmoid(z2) =\n{y[0]}")


y = sigmoid(z2) =
0.7657642942190436


In [10]:
print("\n" + "=" * 50)
print(f"Final Output: {y[0]:.6f}")
print("=" * 50)

# Detailed calculations
print("\nDetailed Calculations:")
print("-" * 50)

print("First Hidden Neuron:")
z1_1 = W1[0,0]*x[0] + W1[0,1]*x[1] + W1[0,2]*x[2] + b1[0]
print(f"z1_1 = {W1[0,0]}*{x[0]} + {W1[0,1]}*{x[1]} + {W1[0,2]}*{x[2]} + {b1[0]} = {z1_1:.6f}")
a1_1 = sigmoid(z1_1)
print(f"a1_1 = sigmoid({z1_1:.6f}) = {a1_1:.6f}")

print("\nSecond Hidden Neuron:")
z1_2 = W1[1,0]*x[0] + W1[1,1]*x[1] + W1[1,2]*x[2] + b1[1]
print(f"z1_2 = {W1[1,0]}*{x[0]} + {W1[1,1]}*{x[1]} + {W1[1,2]}*{x[2]} + {b1[1]} = {z1_2:.6f}")
a1_2 = sigmoid(z1_2)
print(f"a1_2 = sigmoid({z1_2:.6f}) = {a1_2:.6f}")

print("\nOutput Neuron:")
z2_1 = W2[0,0]*a1_1 + W2[0,1]*a1_2 + b2[0]
print(f"z2_1 = {W2[0,0]}*{a1_1:.6f} + {W2[0,1]}*{a1_2:.6f} + {b2[0]} = {z2_1:.6f}")
y = sigmoid(z2_1)
print(f"y = sigmoid({z2_1:.6f}) = {y:.6f}")


Final Output: 0.765764

Detailed Calculations:
--------------------------------------------------
First Hidden Neuron:
z1_1 = 0.5*0.3 + 0.4*0.5 + 0.3*0.2 + 0.4 = 0.810000
a1_1 = sigmoid(0.810000) = 0.692110

Second Hidden Neuron:
z1_2 = 0.4*0.3 + 0.3*0.5 + 0.2*0.2 + 0.4 = 0.710000
a1_2 = sigmoid(0.710000) = 0.670401

Output Neuron:
z2_1 = 0.6*0.692110 + 0.7*0.670401 + 0.3 = 1.184547
y = sigmoid(1.184547) = 0.765764


In [ ]:
import numpy as np

def sigmoid(x):
    """Sigmoid activation function"""
    return 1 / (1 + np.exp(-x))

def relu(x):
    """ReLU activation function"""
    return np.maximum(0, x)

# Network architecture
input_size = 3
hidden_size = 3
output_size = 1

# Input
x = np.array([0.1, 0.2, 0.3])

# Weights and biases
np.random.seed(42)  # For reproducibility
W1 = np.random.randn(hidden_size, input_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(output_size, hidden_size)
b2 = np.random.randn(output_size)

def forward_propagation(x, W1, b1, W2, b2):
    """Perform forward propagation"""
    # Hidden layer
    z1 = np.dot(W1, x) + b1
    a1 = relu(z1)
    
    # Output layer
    z2 = np.dot(W2, a1) + b2
    y = sigmoid(z2)
    
    return z1, a1, z2, y

def print_layer_info(name, W, b, z, a, activation_name):
    """Print detailed information for a layer"""
    print(f"\n{name} Layer:")
    print("-" * 50)
    print(f"Weights:\n{W}")
    print(f"\nBiases:\n{b}")
    print(f"\nWeighted sum (z):\n{z}")
    print(f"\n{activation_name} activation (a):\n{a}")

def print_detailed_calculations(x, W1, b1, W2, b2, z1, a1, z2, y):
    """Print detailed calculations for each neuron"""
    print("\nDetailed Calculations:")
    print("=" * 50)
    
    print("Hidden Layer Neurons:")
    for i in range(hidden_size):
        z = np.dot(W1[i], x) + b1[i]
        a = relu(z)
        print(f"Neuron {i+1}:")
        print(f"  z = {W1[i,0]:.4f}*{x[0]:.4f} + {W1[i,1]:.4f}*{x[1]:.4f} + {W1[i,2]:.4f}*{x[2]:.4f} + {b1[i]:.4f} = {z:.4f}")
        print(f"  a = ReLU({z:.4f}) = {a:.4f}\n")
    
    print("Output Neuron:")
    z = np.dot(W2[0], a1) + b2[0]
    print(f"  z = {W2[0,0]:.4f}*{a1[0]:.4f} + {W2[0,1]:.4f}*{a1[1]:.4f} + {W2[0,2]:.4f}*{a1[2]:.4f} + {b2[0]:.4f} = {z:.4f}")
    print(f"  y = sigmoid({z:.4f}) = {y[0]:.4f}")

# Perform forward propagation
z1, a1, z2, y = forward_propagation(x, W1, b1, W2, b2)

# Print network architecture
print("Neural Network Architecture: 3-3-1")
print("=" * 50)
print(f"Input: {x}")

# Print layer information
print_layer_info("Hidden", W1, b1, z1, a1, "ReLU")
print_layer_info("Output", W2, b2, z2, y, "Sigmoid")

# Print final output
print("\nFinal Output:")
print("-" * 50)
print(f"y = {y[0]:.6f}")

# Print detailed calculations
print_detailed_calculations(x, W1, b1, W2, b2, z1, a1, z2, y)