In [1]:
import numpy as np

In [ ]:
# Regression Problem

In [6]:
import numpy as np

class NeuralNetwork:
    def __init__(self):
        # Input layer values (as shown in diagram)
        self.inputs = np.array([2.4, -1.2, 0.5])
        
        # Weights from input to hidden layer (3x3 matrix)
        self.weights_ih = np.array([
            [0.3, -0.4, 0.7],    # weights from input 1 to hidden nodes
            [0.2, 0.5, -0.6],    # weights from input 2 to hidden nodes
            [-0.1, 0.8, 0.4]     # weights from input 3 to hidden nodes
        ])
        
        # Weights from hidden to output layer (3x1 vector)
        self.weights_ho = np.array([0.5, -0.3, 0.2])
        
        # Bias values
        self.bias_hidden = 1.0    # Hidden layer bias
        self.bias_output = -0.5   # Output layer bias

    def sigmoid(self, x: np.ndarray) -> np.ndarray:
        """Sigmoid activation function"""
        return 1 / (1 + np.exp(-x))

    def format_calculation(self, name: str, inputs: np.ndarray, weights: np.ndarray, 
                         bias: float, show_activation: bool = True) -> str:
        """Format calculation steps in detail"""
        result = f"\n{'='*80}\n{name} Calculations:\n{'='*80}\n"
        
        # Individual weight calculations
        terms = []
        total = 0
        for i, (input_val, weight) in enumerate(zip(inputs, weights)):
            product = input_val * weight
            total += product
            terms.append(f"({input_val:6.3f} × {weight:6.3f} = {product:6.3f})")
        
        # Show each term
        result += "Terms:\n"
        for term in terms:
            result += f"  {term}\n"
        
        # Add bias
        total += bias
        result += f"\nSum of terms: {total - bias:6.3f}"
        result += f"\nAdd bias: {total - bias:6.3f} + {bias:6.3f} = {total:6.3f}"
        
        # Apply activation if required
        if show_activation:
            activated = self.sigmoid(total)
            result += f"\nApply sigmoid activation: {activated:6.3f}"
            return result, activated
        
        return result, total

    def forward_propagation(self) -> tuple:
        """
        Perform forward propagation and return detailed calculations
        """
        output = "NEURAL NETWORK FORWARD PROPAGATION\n"
        
        # Store all values for reference
        values = {
            'input': self.inputs,
            'hidden': np.zeros(3),
            'output': 0
        }
        
        # Show initial values
        output += f"\nINITIAL VALUES:"
        output += f"\nInputs: {self.inputs}"
        output += f"\nInput → Hidden Weights:\n{self.weights_ih}"
        output += f"\nHidden → Output Weights: {self.weights_ho}"
        output += f"\nHidden Layer Bias: {self.bias_hidden}"
        output += f"\nOutput Layer Bias: {self.bias_output}"
        
        # Hidden Layer Calculations
        output += "\n\nHIDDEN LAYER CALCULATIONS:"
        for i in range(3):
            calc, activated = self.format_calculation(
                f"Hidden Node {i+1} (h_{i+1})",
                self.inputs,
                self.weights_ih[:, i],
                self.bias_hidden
            )
            output += calc
            values['hidden'][i] = activated
        
        # Output Layer Calculations
        output += "\n\nOUTPUT LAYER CALCULATIONS:"
        calc, final_output = self.format_calculation(
            "Output Node",
            values['hidden'],
            self.weights_ho,
            self.bias_output,
            show_activation=False  # No activation for regression output
        )
        output += calc
        values['output'] = final_output
        
        # Final Summary
        output += f"\n\n{'='*80}\nFINAL RESULTS:\n{'='*80}"
        output += f"\nInput Layer:  {values['input']}"
        output += f"\nHidden Layer: {values['hidden']}"
        output += f"\nOutput:       {values['output']:.6f}"
        
        return values, output

def main():
    # Create and run the neural network
    nn = NeuralNetwork()
    _, detailed_output = nn.forward_propagation()
    
    # Print the detailed calculations
    print(detailed_output)

if __name__ == "__main__":
    main()

NEURAL NETWORK FORWARD PROPAGATION

INITIAL VALUES:
Inputs: [ 2.4 -1.2  0.5]
Input → Hidden Weights:
[[ 0.3 -0.4  0.7]
 [ 0.2  0.5 -0.6]
 [-0.1  0.8  0.4]]
Hidden → Output Weights: [ 0.5 -0.3  0.2]
Hidden Layer Bias: 1.0
Output Layer Bias: -0.5

HIDDEN LAYER CALCULATIONS:
Hidden Node 1 (h_1) Calculations:
Terms:
  ( 2.400 ×  0.300 =  0.720)
  (-1.200 ×  0.200 = -0.240)
  ( 0.500 × -0.100 = -0.050)

Sum of terms:  0.430
Add bias:  0.430 +  1.000 =  1.430
Apply sigmoid activation:  0.807
Hidden Node 2 (h_2) Calculations:
Terms:
  ( 2.400 × -0.400 = -0.960)
  (-1.200 ×  0.500 = -0.600)
  ( 0.500 ×  0.800 =  0.400)

Sum of terms: -1.160
Add bias: -1.160 +  1.000 = -0.160
Apply sigmoid activation:  0.460
Hidden Node 3 (h_3) Calculations:
Terms:
  ( 2.400 ×  0.700 =  1.680)
  (-1.200 × -0.600 =  0.720)
  ( 0.500 ×  0.400 =  0.200)

Sum of terms:  2.600
Add bias:  2.600 +  1.000 =  3.600
Apply sigmoid activation:  0.973

OUTPUT LAYER CALCULATIONS:
Output Node Calculations:
Terms:
  ( 0.807 × 

In [2]:
class NeuralNetwork:
    def __init__(self):
        # Input layer values
        self.inputs = np.array([2.4, -1.2, 0.5])
        
        # Weights from input to hidden layer
        self.weights_ih = np.array([
            [0.3, -0.4, 0.7],    # weights from input 1 to hidden nodes
            [0.2, 0.5, -0.6],    # weights from input 2 to hidden nodes
            [-0.1, 0.8, 0.4]     # weights from input 3 to hidden nodes
        ])
        
        # Weights from hidden to output layer
        self.weights_ho = np.array([0.5, -0.3, 0.2])
        
        # Bias values
        self.bias_hidden = 1.0
        self.bias_output = -0.5

    def sigmoid(self, x):
        """Sigmoid activation function"""
        return 1 / (1 + np.exp(-x))

    def format_calculation(self, operation_name, inputs, weights, bias, result):
        """Format calculation steps"""
        calc_str = f"\n{'-'*80}\n{operation_name}:\n"
        
        # Format each term in the weighted sum
        terms = [f"({input:.3f} × {weight:.3f})" 
                for input, weight in zip(inputs, weights)]
        
        calc_str += f"Raw calculation: {' + '.join(terms)}"
        if bias is not None:
            calc_str += f" + {bias:.3f} (bias)"
        
        # Calculate intermediate sum before activation
        weighted_sum = np.dot(inputs, weights) + (bias if bias is not None else 0)
        calc_str += f"\nWeighted sum: {weighted_sum:.3f}"
        
        if result != weighted_sum:  # If activation was applied
            calc_str += f"\nAfter activation: {result:.3f}"
            
        return calc_str

    def forward_propagation(self):
        """Perform forward propagation through the network"""
        print(f"\n{'='*80}\nNEURAL NETWORK FORWARD PROPAGATION\n{'='*80}")
        
        # Display initial values
        print("\nINITIAL VALUES:")
        print(f"Inputs: {self.inputs}")
        print(f"Hidden layer weights:\n{self.weights_ih}")
        print(f"Output weights: {self.weights_ho}")
        print(f"Hidden bias: {self.bias_hidden}")
        print(f"Output bias: {self.bias_output}")
        
        print("\nCALCULATIONS:")
        
        # Calculate hidden layer values
        hidden_raw = []
        hidden_activated = []
        
        for i in range(3):  # For each hidden node
            weights = self.weights_ih[:, i]
            raw_value = np.dot(self.inputs, weights) + self.bias_hidden
            activated_value = self.sigmoid(raw_value)
            
            hidden_raw.append(raw_value)
            hidden_activated.append(activated_value)
            
            # Format and display calculation for this hidden node
            print(self.format_calculation(
                f"Hidden Node {i+1}",
                self.inputs,
                weights,
                self.bias_hidden,
                activated_value
            ))
        
        hidden_layer = np.array(hidden_activated)
        
        # Calculate output
        output_raw = np.dot(hidden_layer, self.weights_ho) + self.bias_output
        final_output = self.sigmoid(output_raw)
        
        # Format and display output calculation
        print(self.format_calculation(
            "Output Node",
            hidden_layer,
            self.weights_ho,
            self.bias_output,
            final_output
        ))
        
        # Display final results summary
        print(f"\n{'='*80}\nFINAL RESULTS:\n")
        print("Hidden Layer Values:")
        for i, value in enumerate(hidden_layer, 1):
            print(f"h{i}: {value:.3f}")
        print(f"\nFinal Output: {final_output:.3f}")
        
        return final_output

# Create and run the neural network
nn = NeuralNetwork()
output = nn.forward_propagation()


NEURAL NETWORK FORWARD PROPAGATION

INITIAL VALUES:
Inputs: [ 2.4 -1.2  0.5]
Hidden layer weights:
[[ 0.3 -0.4  0.7]
 [ 0.2  0.5 -0.6]
 [-0.1  0.8  0.4]]
Output weights: [ 0.5 -0.3  0.2]
Hidden bias: 1.0
Output bias: -0.5

CALCULATIONS:

--------------------------------------------------------------------------------
Hidden Node 1:
Raw calculation: (2.400 × 0.300) + (-1.200 × 0.200) + (0.500 × -0.100) + 1.000 (bias)
Weighted sum: 1.430
After activation: 0.807

--------------------------------------------------------------------------------
Hidden Node 2:
Raw calculation: (2.400 × -0.400) + (-1.200 × 0.500) + (0.500 × 0.800) + 1.000 (bias)
Weighted sum: -0.160
After activation: 0.460

--------------------------------------------------------------------------------
Hidden Node 3:
Raw calculation: (2.400 × 0.700) + (-1.200 × -0.600) + (0.500 × 0.400) + 1.000 (bias)
Weighted sum: 3.600
After activation: 0.973

-------------------------------------------------------------------------------

In [1]:
# Two Hidden Nodes
import numpy as np
from typing import Tuple, List, Dict
import json

class NeuralNetwork:
    def __init__(self):
        # Input layer values (3 nodes)
        self.inputs = np.array([2.4, -1.2, 0.5])
        
        # Weights from input to first hidden layer (3x3 matrix)
        self.weights_ih1 = np.array([
            [0.3, -0.4, 0.7],    # weights from input 1 to hidden1 nodes
            [0.2, 0.5, -0.6],    # weights from input 2 to hidden1 nodes
            [-0.1, 0.8, 0.4]     # weights from input 3 to hidden1 nodes
        ])
        
        # Weights from first to second hidden layer (3x3 matrix)
        self.weights_h1h2 = np.array([
            [0.4, -0.2, 0.3],    # weights from hidden1_1 to hidden2 nodes
            [-0.5, 0.6, 0.1],    # weights from hidden1_2 to hidden2 nodes
            [0.2, -0.4, 0.7]     # weights from hidden1_3 to hidden2 nodes
        ])
        
        # Weights from second hidden to output layer (3x1 vector)
        self.weights_h2o = np.array([0.5, -0.3, 0.2])
        
        # Bias values
        self.bias_h1 = 1.0    # First hidden layer bias
        self.bias_h2 = 0.8    # Second hidden layer bias
        self.bias_o = -0.5    # Output layer bias

    def sigmoid(self, x: np.ndarray) -> np.ndarray:
        """Sigmoid activation function"""
        return 1 / (1 + np.exp(-x))
    
    def format_vector_calculation(self, name: str, inputs: np.ndarray, 
                                weights: np.ndarray, bias: float) -> str:
        """Format calculation steps for a vector operation"""
        result = f"\n{'='*100}\n{name} Calculations:\n{'='*100}\n"
        
        # Format each weight calculation
        terms = []
        for i, (inp, weight) in enumerate(zip(inputs, weights)):
            terms.append(f"({inp:6.3f} × {weight:6.3f} = {inp*weight:6.3f})")
        
        # Show the complete calculation
        result += "Weighted sum: " + " + ".join(terms)
        if bias is not None:
            result += f" + {bias:6.3f} (bias)"
        
        # Calculate and show the sum
        weighted_sum = np.dot(inputs, weights) + (bias if bias is not None else 0)
        result += f"\nTotal sum: {weighted_sum:6.3f}"
        
        # Show activation result
        activated = self.sigmoid(weighted_sum)
        result += f"\nAfter sigmoid activation: {activated:6.3f}\n"
        
        return result, activated

    def format_layer_calculations(self, name: str, inputs: np.ndarray, 
                                weights: np.ndarray, bias: float) -> str:
        """Format calculations for an entire layer"""
        result = f"\n{'#'*100}\n{name}\n{'#'*100}"
        activated_values = []
        
        for i in range(weights.shape[1]):
            layer_calc, activated = self.format_vector_calculation(
                f"Node {i+1}",
                inputs,
                weights[:, i],
                bias
            )
            result += layer_calc
            activated_values.append(activated)
        
        return result, np.array(activated_values)

    def forward_propagation(self) -> Tuple[Dict[str, np.ndarray], str]:
        """
        Perform forward propagation through the network and return detailed calculations
        """
        output = "NEURAL NETWORK FORWARD PROPAGATION WITH TWO HIDDEN LAYERS\n"
        
        # Store all layer values for reference
        layer_values = {
            'input': self.inputs
        }
        
        # Input layer information
        output += f"\n{'*'*100}"
        output += "\nINITIAL VALUES:"
        output += f"\nInputs: {self.inputs}"
        output += f"\nFirst Hidden Layer Weights:\n{self.weights_ih1}"
        output += f"\nSecond Hidden Layer Weights:\n{self.weights_h1h2}"
        output += f"\nOutput Weights: {self.weights_h2o}"
        output += f"\nBiases: h1={self.bias_h1}, h2={self.bias_h2}, o={self.bias_o}"
        
        # First Hidden Layer Calculations
        h1_calc, h1_values = self.format_layer_calculations(
            "FIRST HIDDEN LAYER", 
            self.inputs, 
            self.weights_ih1, 
            self.bias_h1
        )
        output += h1_calc
        layer_values['hidden1'] = h1_values
        
        # Second Hidden Layer Calculations
        h2_calc, h2_values = self.format_layer_calculations(
            "SECOND HIDDEN LAYER", 
            h1_values, 
            self.weights_h1h2, 
            self.bias_h2
        )
        output += h2_calc
        layer_values['hidden2'] = h2_values
        
        # Output Layer Calculation
        o_calc, o_value = self.format_vector_calculation(
            "OUTPUT LAYER", 
            h2_values, 
            self.weights_h2o, 
            self.bias_o
        )
        output += f"\n{'#'*100}\nOUTPUT LAYER\n{'#'*100}"
        output += o_calc
        layer_values['output'] = o_value
        
        # Final Summary
        output += f"\n{'='*100}\nFINAL RESULTS:\n{'='*100}\n"
        output += "Layer Values:\n"
        output += f"Input Layer:          {layer_values['input']}\n"
        output += f"First Hidden Layer:   {layer_values['hidden1']}\n"
        output += f"Second Hidden Layer:  {layer_values['hidden2']}\n"
        output += f"Output:               {layer_values['output']}\n"
        
        return layer_values, output

def main():
    # Create and run the neural network
    nn = NeuralNetwork()
    layer_values, detailed_output = nn.forward_propagation()
    
    # Print the detailed calculations
    print(detailed_output)

if __name__ == "__main__":
    main()

NEURAL NETWORK FORWARD PROPAGATION WITH TWO HIDDEN LAYERS

****************************************************************************************************
INITIAL VALUES:
Inputs: [ 2.4 -1.2  0.5]
First Hidden Layer Weights:
[[ 0.3 -0.4  0.7]
 [ 0.2  0.5 -0.6]
 [-0.1  0.8  0.4]]
Second Hidden Layer Weights:
[[ 0.4 -0.2  0.3]
 [-0.5  0.6  0.1]
 [ 0.2 -0.4  0.7]]
Output Weights: [ 0.5 -0.3  0.2]
Biases: h1=1.0, h2=0.8, o=-0.5
####################################################################################################
FIRST HIDDEN LAYER
####################################################################################################
Node 1 Calculations:
Weighted sum: ( 2.400 ×  0.300 =  0.720) + (-1.200 ×  0.200 = -0.240) + ( 0.500 × -0.100 = -0.050) +  1.000 (bias)
Total sum:  1.430
After sigmoid activation:  0.807

Node 2 Calculations:
Weighted sum: ( 2.400 × -0.400 = -0.960) + (-1.200 ×  0.500 = -0.600) + ( 0.500 ×  0.800 =  0.400) +  1.000 (bias)
Total sum: -0.160
After

# Classification Forward Propagation

In [4]:
# Classification Example with One Hidden layer

In [5]:
import numpy as np
from typing import Tuple, Dict

class NeuralNetwork:
    def __init__(self):
        # Input layer values (3 nodes)
        self.inputs = np.array([2.4, -1.2, 0.5])
        
        # Weights from input to hidden layer (3x3 matrix)
        self.weights_ih = np.array([
            [0.3, -0.4, 0.7],    # weights from input 1 to hidden nodes
            [0.2, 0.5, -0.6],    # weights from input 2 to hidden nodes
            [-0.1, 0.8, 0.4]     # weights from input 3 to hidden nodes
        ])
        
        # Weights from hidden to output layer (3x2 matrix)
        self.weights_ho = np.array([
            [0.5, 0.4],     # weights from hidden 1 to output nodes
            [-0.3, 0.6],    # weights from hidden 2 to output nodes
            [0.2, -0.3]     # weights from hidden 3 to output nodes
        ])
        
        # Bias values
        self.bias_hidden = 1.0               # Hidden layer bias
        self.bias_output = np.array([-0.5, 0.4])  # Output layer biases

    def sigmoid(self, x: np.ndarray) -> np.ndarray:
        """Sigmoid activation function"""
        return 1 / (1 + np.exp(-x))
    
    def format_vector_calculation(self, name: str, inputs: np.ndarray, 
                                weights: np.ndarray, bias: float) -> Tuple[str, float]:
        """Format calculation steps for a vector operation"""
        result = f"\n{'='*100}\n{name} Calculations:\n{'='*100}\n"
        
        # Format each weight calculation
        terms = []
        weighted_terms = []
        for i, (inp, weight) in enumerate(zip(inputs, weights)):
            terms.append(f"({inp:6.3f} × {weight:6.3f})")
            weighted_terms.append(inp * weight)
            
        # Show the complete calculation
        result += "Terms: " + " + ".join(terms)
        if bias is not None:
            result += f" + {bias:6.3f} (bias)"
        
        # Show individual results
        result += "\nWeighted terms: ["
        result += ", ".join([f"{term:6.3f}" for term in weighted_terms])
        result += "]"
        
        # Calculate and show the sum
        weighted_sum = np.sum(weighted_terms) + (bias if bias is not None else 0)
        result += f"\nWeighted sum: {weighted_sum:6.3f}"
        
        # Show activation result
        activated = self.sigmoid(weighted_sum)
        result += f"\nAfter sigmoid activation: {activated:6.3f}\n"
        
        return result, activated

    def format_layer_calculations(self, name: str, inputs: np.ndarray, 
                                weights: np.ndarray, bias: float) -> Tuple[str, np.ndarray]:
        """Format calculations for an entire layer"""
        result = f"\n{'#'*100}\n{name}\n{'#'*100}"
        activated_values = []
        
        for i in range(weights.shape[1]):
            layer_calc, activated = self.format_vector_calculation(
                f"Node {i+1}",
                inputs,
                weights[:, i],
                bias if np.isscalar(bias) else bias[i]
            )
            result += layer_calc
            activated_values.append(activated)
        
        return result, np.array(activated_values)

    def forward_propagation(self) -> Tuple[Dict[str, np.ndarray], str]:
        """
        Perform forward propagation through the network and return detailed calculations
        """
        output = f"{'='*100}\n"
        output += "NEURAL NETWORK FORWARD PROPAGATION\n"
        output += f"Single Hidden Layer with Two Outputs\n{'='*100}\n"
        
        # Store all layer values
        layer_values = {
            'input': self.inputs
        }
        
        # Display initial values
        output += "\nNETWORK CONFIGURATION:"
        output += f"\nInput values: {self.inputs}"
        output += f"\n\nWeights (Input → Hidden):\n{self.weights_ih}"
        output += f"\n\nWeights (Hidden → Output):\n{self.weights_ho}"
        output += f"\n\nBias values:"
        output += f"\n  Hidden layer: {self.bias_hidden}"
        output += f"\n  Output layer: {self.bias_output}"
        
        # Hidden Layer Calculations
        hidden_calc, hidden_values = self.format_layer_calculations(
            "HIDDEN LAYER", 
            self.inputs, 
            self.weights_ih, 
            self.bias_hidden
        )
        output += hidden_calc
        layer_values['hidden'] = hidden_values
        
        # Output Layer Calculations
        output_calc, output_values = self.format_layer_calculations(
            "OUTPUT LAYER", 
            hidden_values, 
            self.weights_ho, 
            self.bias_output
        )
        output += output_calc
        layer_values['output'] = output_values
        
        # Final Summary
        output += f"\n{'='*100}\nFINAL RESULTS\n{'='*100}\n"
        output += "\nLayer Values:"
        output += f"\nInput Layer:   {layer_values['input']}"
        output += f"\nHidden Layer:  {layer_values['hidden']}"
        output += "\nOutput Layer:"
        output += f"\n  Output 1:    {layer_values['output'][0]:.6f}"
        output += f"\n  Output 2:    {layer_values['output'][1]:.6f}"
        
        return layer_values, output

def main():
    # Create and run the neural network
    nn = NeuralNetwork()
    _, detailed_output = nn.forward_propagation()
    
    # Print the detailed calculations
    print(detailed_output)

if __name__ == "__main__":
    main()

NEURAL NETWORK FORWARD PROPAGATION
Single Hidden Layer with Two Outputs

NETWORK CONFIGURATION:
Input values: [ 2.4 -1.2  0.5]

Weights (Input → Hidden):
[[ 0.3 -0.4  0.7]
 [ 0.2  0.5 -0.6]
 [-0.1  0.8  0.4]]

Weights (Hidden → Output):
[[ 0.5  0.4]
 [-0.3  0.6]
 [ 0.2 -0.3]]

Bias values:
  Hidden layer: 1.0
  Output layer: [-0.5  0.4]
####################################################################################################
HIDDEN LAYER
####################################################################################################
Node 1 Calculations:
Terms: ( 2.400 ×  0.300) + (-1.200 ×  0.200) + ( 0.500 × -0.100) +  1.000 (bias)
Weighted terms: [ 0.720, -0.240, -0.050]
Weighted sum:  1.430
After sigmoid activation:  0.807

Node 2 Calculations:
Terms: ( 2.400 × -0.400) + (-1.200 ×  0.500) + ( 0.500 ×  0.800) +  1.000 (bias)
Weighted terms: [-0.960, -0.600,  0.400]
Weighted sum: -0.160
After sigmoid activation:  0.460

Node 3 Calculations:
Terms: ( 2.400 ×  0.700) + (-

In [3]:
# Two Hidden Layers Two Output nodes: Classification 
# ==================================================

import numpy as np
from typing import Tuple, List, Dict
import json

class NeuralNetwork:
    def __init__(self):
        # Input layer values (3 nodes)
        self.inputs = np.array([2.4, -1.2, 0.5])
        
        # Weights from input to first hidden layer (3x3 matrix)
        self.weights_ih1 = np.array([
            [0.3, -0.4, 0.7],    # weights from input 1 to hidden1 nodes
            [0.2, 0.5, -0.6],    # weights from input 2 to hidden1 nodes
            [-0.1, 0.8, 0.4]     # weights from input 3 to hidden1 nodes
        ])
        
        # Weights from first to second hidden layer (3x3 matrix)
        self.weights_h1h2 = np.array([
            [0.4, -0.2, 0.3],    # weights from hidden1_1 to hidden2 nodes
            [-0.5, 0.6, 0.1],    # weights from hidden1_2 to hidden2 nodes
            [0.2, -0.4, 0.7]     # weights from hidden1_3 to hidden2 nodes
        ])
        
        # Weights from second hidden to output layer (3x2 matrix)
        self.weights_h2o = np.array([
            [0.5, 0.4],     # weights from hidden2_1 to output nodes
            [-0.3, 0.6],    # weights from hidden2_2 to output nodes
            [0.2, -0.3]     # weights from hidden2_3 to output nodes
        ])
        
        # Bias values
        self.bias_h1 = 1.0                # First hidden layer bias
        self.bias_h2 = 0.8                # Second hidden layer bias
        self.bias_o = np.array([-0.5, 0.4])  # Output layer biases

    def sigmoid(self, x: np.ndarray) -> np.ndarray:
        """Sigmoid activation function"""
        return 1 / (1 + np.exp(-x))
    
    def format_vector_calculation(self, name: str, inputs: np.ndarray, 
                                weights: np.ndarray, bias: float) -> str:
        """Format calculation steps for a vector operation"""
        result = f"\n{'='*100}\n{name} Calculations:\n{'='*100}\n"
        
        # Format each weight calculation
        terms = []
        for i, (inp, weight) in enumerate(zip(inputs, weights)):
            terms.append(f"({inp:6.3f} × {weight:6.3f} = {inp*weight:6.3f})")
        
        # Show the complete calculation
        result += "Weighted sum: " + " + ".join(terms)
        if bias is not None:
            result += f" + {bias:6.3f} (bias)"
        
        # Calculate and show the sum
        weighted_sum = np.dot(inputs, weights) + (bias if bias is not None else 0)
        result += f"\nTotal sum: {weighted_sum:6.3f}"
        
        # Show activation result
        activated = self.sigmoid(weighted_sum)
        result += f"\nAfter sigmoid activation: {activated:6.3f}\n"
        
        return result, activated

    def format_layer_calculations(self, name: str, inputs: np.ndarray, 
                                weights: np.ndarray, bias: float) -> str:
        """Format calculations for an entire layer"""
        result = f"\n{'#'*100}\n{name}\n{'#'*100}"
        activated_values = []
        
        for i in range(weights.shape[1]):
            layer_calc, activated = self.format_vector_calculation(
                f"Node {i+1}",
                inputs,
                weights[:, i],
                bias if np.isscalar(bias) else bias[i]
            )
            result += layer_calc
            activated_values.append(activated)
        
        return result, np.array(activated_values)

    def forward_propagation(self) -> Tuple[Dict[str, np.ndarray], str]:
        """
        Perform forward propagation through the network and return detailed calculations
        """
        output = "NEURAL NETWORK FORWARD PROPAGATION WITH TWO HIDDEN LAYERS AND TWO OUTPUTS\n"
        
        # Store all layer values for reference
        layer_values = {
            'input': self.inputs
        }
        
        # Input layer information
        output += f"\n{'*'*100}"
        output += "\nINITIAL VALUES:"
        output += f"\nInputs: {self.inputs}"
        output += f"\nFirst Hidden Layer Weights:\n{self.weights_ih1}"
        output += f"\nSecond Hidden Layer Weights:\n{self.weights_h1h2}"
        output += f"\nOutput Layer Weights:\n{self.weights_h2o}"
        output += f"\nBiases: h1={self.bias_h1}, h2={self.bias_h2}, o={self.bias_o}"
        
        # First Hidden Layer Calculations
        h1_calc, h1_values = self.format_layer_calculations(
            "FIRST HIDDEN LAYER", 
            self.inputs, 
            self.weights_ih1, 
            self.bias_h1
        )
        output += h1_calc
        layer_values['hidden1'] = h1_values
        
        # Second Hidden Layer Calculations
        h2_calc, h2_values = self.format_layer_calculations(
            "SECOND HIDDEN LAYER", 
            h1_values, 
            self.weights_h1h2, 
            self.bias_h2
        )
        output += h2_calc
        layer_values['hidden2'] = h2_values
        
        # Output Layer Calculations
        output_calc = f"\n{'#'*100}\nOUTPUT LAYER\n{'#'*100}"
        output_values = []
        
        for i in range(self.weights_h2o.shape[1]):
            calc, activated = self.format_vector_calculation(
                f"Output Node {i+1}",
                h2_values,
                self.weights_h2o[:, i],
                self.bias_o[i]
            )
            output_calc += calc
            output_values.append(activated)
        
        output += output_calc
        layer_values['output'] = np.array(output_values)
        
        # Final Summary
        output += f"\n{'='*100}\nFINAL RESULTS:\n{'='*100}\n"
        output += "Layer Values:\n"
        output += f"Input Layer:          {layer_values['input']}\n"
        output += f"First Hidden Layer:   {layer_values['hidden1']}\n"
        output += f"Second Hidden Layer:  {layer_values['hidden2']}\n"
        output += "Output Layer:\n"
        output += f"  Output 1:           {layer_values['output'][0]:.3f}\n"
        output += f"  Output 2:           {layer_values['output'][1]:.3f}\n"
        
        return layer_values, output

def main():
    # Create and run the neural network
    nn = NeuralNetwork()
    layer_values, detailed_output = nn.forward_propagation()
    
    # Print the detailed calculations
    print(detailed_output)

if __name__ == "__main__":
    main()

NEURAL NETWORK FORWARD PROPAGATION WITH TWO HIDDEN LAYERS AND TWO OUTPUTS

****************************************************************************************************
INITIAL VALUES:
Inputs: [ 2.4 -1.2  0.5]
First Hidden Layer Weights:
[[ 0.3 -0.4  0.7]
 [ 0.2  0.5 -0.6]
 [-0.1  0.8  0.4]]
Second Hidden Layer Weights:
[[ 0.4 -0.2  0.3]
 [-0.5  0.6  0.1]
 [ 0.2 -0.4  0.7]]
Output Layer Weights:
[[ 0.5  0.4]
 [-0.3  0.6]
 [ 0.2 -0.3]]
Biases: h1=1.0, h2=0.8, o=[-0.5  0.4]
####################################################################################################
FIRST HIDDEN LAYER
####################################################################################################
Node 1 Calculations:
Weighted sum: ( 2.400 ×  0.300 =  0.720) + (-1.200 ×  0.200 = -0.240) + ( 0.500 × -0.100 = -0.050) +  1.000 (bias)
Total sum:  1.430
After sigmoid activation:  0.807

Node 2 Calculations:
Weighted sum: ( 2.400 × -0.400 = -0.960) + (-1.200 ×  0.500 = -0.600) + ( 0.500 ×  0.8